### ISSUE TITLE
Handle punctuation correctly

### ISSUE THREAD

**Issue by RoryOfByrne** [RoryOfByrne/ronald-trump#10]
Right now, every token of output is separated by a space. This means that " sentences look like this . with punctuation spaced " .

We should add some post-processing in `generate()` to handle punctuation correctly.

**Comment by SuzanneMcC** [comment]
Do you want to just do re.sub(r'[^a-zA-Z0-9]','', your_string), or something more selective?  Hash-tags would probably be worth saving, obv.

**Comment by RoryOfByrne** [comment]
Taking the latest tweet as an example: 

`we are going to do better , most imaginative #votetrumpnc . great news ! just won iowa to make america great again ! !`

The punctuation should be placed correctly to produce an output like this: 

`we are going to do better, most imaginative #votetrumpnc. great news! just won iowa to make america great again!!`

A good start would be to add functionality to `Generator.generate()` to post-process the output and fix commas, full-stops, exclamation marks, question marks, colons, and semi-colons. i.e. the punctuation which has a space afterwards but not before. We do want to preserve hashtags.

**Comment by RoryOfByrne** [comment]
I implemented a quick regex for punctuation with trailing spaces. 

I'm going to add another postprocessing function which removes quotes and parentheses completely because they're never going to make sense in a randomly generated piece of text unless the system can actually produce semantically viable text (i.e. not this system).

Another one to do is capitalizing words correctly. This can be done by splitting the output into sentences using the Punkt Tokenizer (see `Preprocessor.split_into_sentences()`) and capitalizing the first words, then re-combining the sentences. We'll need named-entity recognition to handle capitalization inside a sentence.
